-- Create TASKS table to store all tasks
CREATE TABLE IF NOT EXISTS TASKS(
    TID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    DURATION INT,
    CATEGORY CHAR(50),
    POINTS INT NOT NULL,
    DIRECTORY TEXT,
    P_TID INT,
    FOREIGN KEY (P_TID) REFERENCES TASKS (TID)
);

-- Create TASKTAG table to link tags to tasks
CREATE TABLE IF NOT EXISTS TASKTAG(
    TID INT NOT NULL,
    TAG CHAR(50) NOT NULL,
    PRIMARY KEY (TID, TAG),
    FOREIGN KEY (TID) REFERENCES TASKS (TID)
);

-- Index for faster tag queries
CREATE INDEX IF NOT EXISTS idx_task_tags ON TASKTAG (TAG);

